name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release:
    if: github.repository == 'urbanairship/android-library'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Get the release notes
        id: get_release_notes
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          NOTES="$(awk "/## Version $VERSION/{flag=1;next}/## Version/{flag=0}flag" CHANGELOG.md)"
          NOTES="${NOTES//'%'/'%25'}"
          NOTES="${NOTES//$'\n'/'%0A'}"
          NOTES="${NOTES//$'\r'/'%0D'}"
          echo ::set-output name=NOTES::"$NOTES"

      - name: Verify Version
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          if [[ $(./gradlew -q getVersion) = $VERSION ]]; then exit 0 ; else exit 1; fi

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup GCP
        uses: google-github-actions/setup-gcloud@daadedc81d5f9d3c06d2c92f49202a3cc2b919ba # v0.2.1
        with:
          version: '351.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Build
        run: ./gradlew assembleRelease packageDocs --stacktrace

      - name: Upload docs
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          gsutil cp build/docs/$VERSION.tar.gz gs://ua-web-ci-prod-docs-transfer/libraries/android/$VERSION.tar.gz
          gsutil cp build/docs/$VERSION-kdoc.tar.gz gs://ua-web-ci-prod-docs-transfer/libraries/android-kotlin/$VERSION.tar.gz

      - name: Github Release
        uses: actions/create-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.get_release_notes.outputs.NOTES }}
          draft: false
          prerelease: false

      - name: Publish to Maven Central
        env:
          SONATYPE_USERNAME: ${{ secrets.MAVEN_USER }}
          SONATYPE_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.MAVEN_STAGING_PROFILE_ID }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: >-
          ./gradlew
          urbanairship-core:publishProductionPublicationToSonatypeRepository
          urbanairship-layout:publishProductionPublicationToSonatypeRepository
          urbanairship-automation:publishProductionPublicationToSonatypeRepository
          urbanairship-message-center:publishProductionPublicationToSonatypeRepository
          urbanairship-location:publishProductionPublicationToSonatypeRepository
          urbanairship-ads-identifier:publishProductionPublicationToSonatypeRepository
          urbanairship-preference:publishProductionPublicationToSonatypeRepository
          urbanairship-accengage:publishProductionPublicationToSonatypeRepository
          urbanairship-fcm:publishProductionPublicationToSonatypeRepository
          urbanairship-adm:publishProductionPublicationToSonatypeRepository
          urbanairship-hms:publishProductionPublicationToSonatypeRepository
          urbanairship-chat:publishProductionPublicationToSonatypeRepository
          urbanairship-preference-center:publishProductionPublicationToSonatypeRepository
          --stacktrace
          --max-workers 1
          closeAndReleaseSonatypeStagingRepository
